//
//  SettingsInteractor.swift
//  Tinder_Analog
//
//  Created Vitaly on 23.10.2019.
//  Copyright © 2019 Vitaly. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/Swift-viper-template-for-xcode
//

import UIKit

class SettingsInteractor: SettingsInteractorInput {
    // MARK: - Properties
    weak var presenter: SettingsInteractorOutput?
    
    // MARK: - SettingsInteractorInput -

}

extension SettingsInteractor {
    func fetchUserData() {
        UserDataManager.fetchUserData()
        .done { [weak self] (userData) in
            self?.presenter?.fetchedUserData(userData: userData)
        }
        .catch { [weak self] (error) in
            self?.presenter?.fetchedUserData(with: error)
        }
        .finally { }
    }
    
    func fetchUserPhotos(imageUrls: [String]) {
        UserDataManager.fetchUserPhotos(imageUrls: imageUrls)
        .done { [weak self] (photos) in
            self?.presenter?.fetchedUsersPhotos(userPhotos: photos)
        }
        .catch { [weak self] (error) in
            self?.presenter?.fetchedUserData(with: error)
        }
        .finally { }
    }
}
