//
//  SettingsRouter.swift
//  Tinder_Analog
//
//  Created Vitaly on 23.10.2019.
//  Copyright © 2019 Vitaly. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/Swift-viper-template-for-xcode
//

import UIKit

class SettingsRouter {
    // MARK: - Properties
    weak var viewController: UIViewController?
}

// MARK: - SettingsWireframeInterface -
extension SettingsRouter: SettingsWireframeInterface {
    
    func navigate(to option: SettingsNavigationOption) {
//        let vc: UIViewController!
        switch option {
        case .mainScreen:
            viewController?.dismiss(animated: true)
            return
        }
//        if vc is UINavigationController {
//            viewController?.present(vc, animated: true, completion: nil)
//        } else {
//            viewController?.navigationController?.pushViewController(vc, animated: true)
//        }
    }
}
