//
//  SettingsConfigurator.swift
//  Tinder_Analog
//
//  Created Vitaly on 23.10.2019.
//  Copyright © 2019 Vitaly. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/Swift-viper-template-for-xcode
//

import UIKit

struct SettingsConfigurator {

	static func createModule() -> UIViewController {
        var view: SettingsViewController!

        let viewController = UIStoryboard.init(name: "Settings", bundle: Bundle.main).instantiateInitialViewController()
//        viewController?.modalPresentationStyle = .
        if viewController == nil {
            fatalError("Seems there is no initial view controller in Settings.storyboard")
        }

        if viewController is UINavigationController {
            view = (viewController as? UINavigationController)?.viewControllers.first as? SettingsViewController
        } else {
            view = viewController as? SettingsViewController
        }

        let interactor = SettingsInteractor()
        let router = SettingsRouter()
        let presenter = SettingsPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return viewController!
    }
}
