//
//  RegistrationRouter.swift
//  Tinder_Analog
//
//  Created Vitaly on 12.10.2019.
//  Copyright © 2019 Vitaly. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/Swift-viper-template-for-xcode
//

import UIKit

class RegistrationRouter {
    // MARK: - Properties
    weak var viewController: UIViewController?
}

// MARK: - RegistrationWireframeInterface -
extension RegistrationRouter: RegistrationWireframeInterface {
    
    func navigate(to option: RegistrationNavigationOption) {
//        switch option {
//        case .firstModule:
//              openFirstModule()
//        case .secondModule(let someData):
        //      openSecondModule(with someData)
//        }
    }
}
