//
//  HomeScreenConfigurator.swift
//  Tinder_Analog
//
//  Created Vitaly on 08/10/2019.
//  Copyright © 2019 Vitaly. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/Swift-viper-template-for-xcode
//

import UIKit

struct HomeScreenConfigurator {

	static func createModule() -> UIViewController {
        var view: HomeScreenViewController!

        let viewController = UIStoryboard.init(name: "HomeScreen", bundle: Bundle.main).instantiateInitialViewController()
        if viewController == nil {
            fatalError("Seems there is no initial view controller in HomeScreen.storyboard")
        }

        if viewController is UINavigationController {
            view = (viewController as! UINavigationController).viewControllers.first as? HomeScreenViewController
        } else {
            view = viewController as? HomeScreenViewController
        }

        let interactor = HomeScreenInteractor()
        let router = HomeScreenRouter()
        let presenter = HomeScreenPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return viewController!
    }
}
