//
//  HomeScreenRouter.swift
//  Tinder_Analog
//
//  Created Vitaly on 08/10/2019.
//  Copyright © 2019 Vitaly. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/Swift-viper-template-for-xcode
//

import UIKit

class HomeScreenRouter {
    // MARK: - Properties
    weak var viewController: UIViewController?
}

// MARK: - HomeScreenWireframeInterface -
extension HomeScreenRouter: HomeScreenWireframeInterface {
    
    func navigate(to option: HomeScreenNavigationOption) {
//        switch option {
//        case .firstModule:
//              openFirstModule()
//        case .secondModule(let someData):
        //      openSecondModule(with someData)
//        }
    }
}
