//
//  HomeScreenPresenter.swift
//  Tinder_Analog
//
//  Created Vitaly on 08/10/2019.
//  Copyright © 2019 Vitaly. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/Swift-viper-template-for-xcode
//

import UIKit

class HomeScreenPresenter {
    // MARK: - Properties
    weak private var view: HomeScreenView?
    var interactor: HomeScreenInteractorInput?
    private let router: HomeScreenWireframeInterface

    // MARK: - Initialization and deinitialization -
    init(interface: HomeScreenView, interactor: HomeScreenInteractorInput?, router: HomeScreenWireframeInterface) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}

// MARK: - HomeScreenPresenterInterface -
extension HomeScreenPresenter: HomeScreenPresenterInterface {
    
    func viewWillAppear() {
       
    }
    func viewDidLoad() {
         displayData()
    }
}

// MARK: - HomeScreenInteractorOutput -
extension HomeScreenPresenter: HomeScreenInteractorOutput {
    
}

// MARK: - Private methods
extension HomeScreenPresenter {
    private func displayData() {
        
        let oneData = CardView.Data(name: "Лиза", age: "23", profession: "programmer", imageNames: ["kelly1", "kelly2", "kelly3"])
        let twoData = CardView.Data(name: "Лиза", age: "23", profession: "programmer", imageNames: ["123"])
        let advertise = CardView.Data(name: "Johanna", age: nil, profession: "dsjdh", imageNames: ["jane1", "jane2", "jane3"])
        
        view?.displayData([oneData, twoData, advertise])
        
    }

}

