//
//  HomeScreenInteractor.swift
//  Tinder_Analog
//
//  Created Vitaly on 08/10/2019.
//  Copyright © 2019 Vitaly. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/Swift-viper-template-for-xcode
//

import UIKit

class HomeScreenInteractor: HomeScreenInteractorInput {
    // MARK: - Properties
    weak var presenter: HomeScreenInteractorOutput?
    
    // MARK: - HomeScreenInteractorInput -

}
