//
//  HomeScreenViewController.swift
//  Tinder_Analog
//
//  Created Vitaly on 08/10/2019.
//  Copyright © 2019 Vitaly. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/Swift-viper-template-for-xcode
//

import UIKit

class HomeScreenViewController: UIViewController {
    // MARK: - Properties
    var presenter: HomeScreenPresenterInterface?
    let topStackView = TopNavigationStackView()
    let cardsDeckView = UIView()
    let buttonsStackView = HomeBottomControlsStackView()
    var cardViewData: [CardView.Data]? = []
    
    // MARK: - Lifecycle -
    override func viewDidLoad() {
        super.viewDidLoad()
        configureUI()
        presenter?.viewDidLoad()
        setup()
    }
    
}

// MARK: - UI Configuration
extension HomeScreenViewController {
    private func configureUI() {
        let overallStackView = UIStackView(arrangedSubviews: [topStackView, cardsDeckView, buttonsStackView])
        overallStackView.axis = .vertical
        view.addSubview(overallStackView)
        overallStackView.anchor(top: view.safeAreaLayoutGuide.topAnchor, leading: view.leadingAnchor, bottom: view.safeAreaLayoutGuide.bottomAnchor, trailing: view.trailingAnchor)
        overallStackView.isLayoutMarginsRelativeArrangement = true
        overallStackView.layoutMargins = .init(top: 0, left: 12, bottom: 0, right: 12)
        
        overallStackView.bringSubviewToFront(cardsDeckView)
    }
    
    private func setup() {
        cardViewData?.forEach({ (data) in
            let cardView = CardView(data: data)
            cardsDeckView.addSubview(cardView)
            cardView.fillSuperview()
        })
    }
}


// MARK: - HomeScreenView
extension HomeScreenViewController: HomeScreenView {
    func displayData(_ data: [CardView.Data]) {
        cardViewData = data
    }
}
