//
//  HomeScreenRouter.swift
//  Tinder_Analog
//
//  Created Vitaly on 08/10/2019.
//  Copyright © 2019 Vitaly. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/Swift-viper-template-for-xcode
//

import UIKit

class HomeScreenRouter {
    // MARK: - Properties
    weak var viewController: UIViewController?
}

// MARK: - HomeScreenWireframeInterface -
extension HomeScreenRouter: HomeScreenWireframeInterface {
    
    func navigate(to option: HomeScreenNavigationOption) {
        let vc: UIViewController!
        switch option {
        case .settingsVC:
            vc = SettingsConfigurator.createModule()
        }
//        if vc is UINavigationController {
            viewController?.present(vc, animated: true, completion: nil)
//        } else {
//            viewController?.navigationController?.pushViewController(vc, animated: true)
//        }
    }
}
