//
//  HomeScreenInteractor.swift
//  Tinder_Analog
//
//  Created Vitaly on 08/10/2019.
//  Copyright © 2019 Vitaly. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/Swift-viper-template-for-xcode
//

import UIKit
import Firebase

class HomeScreenInteractor: HomeScreenInteractorInput {
    
    
    // MARK: - Properties
    weak var presenter: HomeScreenInteractorOutput?
    var usersData: [User]?
    
    // MARK: - HomeScreenInteractorInput -
    
    func fetchDataFirebase() {
        Firestore.firestore().collection("Users").getDocuments { (snapshot, err) in
            if let err = err {
                print("Failed to fetch users:", err)
                return
            }
            snapshot?.documents.forEach { (documentSnapshot) in
                let userDictionary = documentSnapshot.data()
                let user = User(dictionary: userDictionary)
                self.presenter?.fetchedData(data: [user])
//                self.usersData?.append(user)
            }
//            self.presenter?.fetchedData(data: self.usersData ?? [])
        }
    }
}
